#  Copyright (c) University College London Hospitals NHS Foundation Trust
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Default configuration for base with commented links to their respective image modalities

- name: "Private Creator Data Element"
  group: 0x000d
  element: 0x0010
  op: "keep"
- name: "UCLH Project Name"
  group: 0x000d
  element: 0x1001
  op: "keep"
####### 0008 Group #######
- name: "Specific Character Set"
  group: 0x0008
  element: 0x0005
  op: "keep"
#https://dicom.innolitics.com/ciods/ct-image/sop-common/00080005
#https://dicom.innolitics.com/ciods/mr-image/sop-common/00080005
#https://dicom.innolitics.com/ciods/ultrasound-image/sop-common/00080005
#https://dicom.innolitics.com/ciods/rt-image/sop-common/00080005
- name: "Image Type"
  group: 0x0008
  element: 0x0008
  op: "keep"
#https://dicom.innolitics.com/ciods/computed-radiography-image/general-image/00080008
#https://dicom.innolitics.com/ciods/ct-image/general-image/00080008
#https://dicom.innolitics.com/ciods/mr-image/general-image/00080008
#https://dicom.innolitics.com/ciods/ultrasound-image/general-image/00080008
#https://dicom.innolitics.com/ciods/nuclear-medicine-image/general-image/00080008
#https://dicom.innolitics.com/ciods/secondary-capture-image/general-image/00080008
#https://dicom.innolitics.com/ciods/rt-image/general-image/00080008
#https://dicom.innolitics.com/ciods/video-endoscopic-image/general-image/00080008
#https://dicom.innolitics.com/ciods/vl-microscopic-image/general-image/00080008
#https://dicom.innolitics.com/ciods/vl-photographic-image/general-image/00080008
#https://dicom.innolitics.com/ciods/vl-endoscopic-image/general-image/00080008
#https://dicom.innolitics.com/ciods/video-photographic-image/general-image/00080008
#https://dicom.innolitics.com/ciods/video-microscopic-image/general-image/00080008
#https://dicom.innolitics.com/ciods/dermoscopic-photography-image/general-image/00080008
#https://dicom.innolitics.com/ciods/photoacoustic-image/general-image/00080008
#https://dicom.innolitics.com/ciods/confocal-microscopy-image/general-image/00080008
- name: "Instance Creator UID"
  group: 0x0008
  element: 0x0014
  op: "replace_UID"
#https://dicom.innolitics.com/ciods/ct-image/sop-common/00080014
#https://dicom.innolitics.com/ciods/mr-image/sop-common/00080014
#https://dicom.innolitics.com/ciods/ultrasound-image/sop-common/00080014
#https://dicom.innolitics.com/ciods/rt-image/sop-common/00080014
#NOTE: Not sure if the following ones are need here but just put them in case we need them,
#      otherwise we remove anything different from image modality!
#https://dicom.innolitics.com/ciods/rt-plan/sop-common/00080014
#https://dicom.innolitics.com/ciods/rt-dose/sop-common/00080014
#https://dicom.innolitics.com/ciods/enhanced-sr/sop-common/00080014
#https://dicom.innolitics.com/ciods/sleep-electroencephalogram/sop-common/00080014
#https://dicom.innolitics.com/ciods/hemodynamic-waveform/sop-common/00080014
#https://dicom.innolitics.com/ciods/respiratory-waveform/sop-common/00080014
#https://dicom.innolitics.com/ciods/ambulatory-ecg/sop-common/00080014
#https://dicom.innolitics.com/ciods/general-ecg/sop-common/00080014
#https://dicom.innolitics.com/ciods/electromyogram/sop-common/00080014
#https://dicom.innolitics.com/ciods/electrooculogram/sop-common/00080014
#https://dicom.innolitics.com/ciods/comprehensive-sr/sop-common/00080014
#https://dicom.innolitics.com/ciods/procedure-log/sop-common/00080014
#https://dicom.innolitics.com/ciods/extensible-sr/sop-common/00080014
#https://dicom.innolitics.com/ciods/mr-spectroscopy/sop-common/00080014
#https://dicom.innolitics.com/ciods/spatial-registration/sop-common/00080014
#https://dicom.innolitics.com/ciods/raw-data/sop-common/00080014
#https://dicom.innolitics.com/ciods/encapsulated-pdf/sop-common/00080014
#https://dicom.innolitics.com/ciods/spatial-fiducials/sop-common/00080014
#https://dicom.innolitics.com/ciods/stereometric-relationship/sop-common/00080014
#https://dicom.innolitics.com/ciods/hanging-protocol/sop-common/00080014
#...
#NOTE List of searched term continutes
- name: "SOP Class UID"
  group: 0x0008
  element: 0x0016
  op: "keep"
#https://dicom.innolitics.com/ciods/mr-image/sop-common/00080016
#https://dicom.innolitics.com/ciods/ct-image/sop-common/00080016
#https://dicom.innolitics.com/ciods/ultrasound-image/sop-common/00080016
#https://dicom.innolitics.com/ciods/rt-image/sop-common/00080016
#https://dicom.innolitics.com/ciods/mr-spectroscopy/sop-common/00080016
#NOTE List of searched term continutes
- name: "SOP Instance UID"
  group: 0x0008
  element: 0x0018
  op: "replace_UID"
#https://dicom.innolitics.com/ciods/mr-image/sop-common/00080018
#https://dicom.innolitics.com/ciods/ct-image/sop-common/00080018
#https://dicom.innolitics.com/ciods/rt-image/sop-common/00080018
#https://dicom.innolitics.com/ciods/mr-spectroscopy/sop-common/00080018
#NOTE List of searched term continutes
- name: "Accession Number"
  group: 0x0008
  element: 0x0050
  op: "replace"
- name: "Study Date"
  group: 0x0008
  element: 0x0020
  op: "replace"
- name: "General Study"
  group: 0x0008
  element: 0x0030
  op: "replace"
- name: "Modality"
  group: 0x0008
  element: 0x0060
  op: "keep"
- name: "Modalities In Study"
  group: 0x0008
  element: 0x0061
  op: "keep"
- name: "Manufacturer"
  group: 0x0008
  element: 0x0070
  op: "keep"
- name: "Referring Physician's Name"
  group: 0x0008
  element: 0x0090
  op: "replace"
- name: "Study Description"
  group: 0x0008
  element: 0x1030
  op: "keep"
- name: "Series Description"
  group: 0x0008
  element: 0x103e
  op: "keep"
- name: "Manufacturers Model Name"
  group: 0x0008
  element: 0x1090
  op: "keep"
- name: "Referenced Series Sequence"
  group: 0x0008
  element: 0x1155
  op: "replace_UID"
- name: "Referenced Frame Number"
  group: 0x0008
  element: 0x1160
  op: "keep"
- name: "Pixel Presentation"
  group: 0x0008
  element: 0x9205
  op: "keep"
- name: "Volumetric Properties"
  group: 0x0008
  element: 0x9206
  op: "keep"
- name: "Volume Based Calculation Technique Attribute"
  group: 0x0008
  element: 0x9207
  op: "keep"
- name: "Complex Image Component"
  group: 0x0008
  element: 0x9208
  op: "keep"
- name: "Acquisition Contrast"
  group: 0x0008
  element: 0x9209
  op: "keep"
####### 0010 Group #######
- name: "Patients Name"
  group: 0x0010
  element: 0x0010
  op: "replace"
#https://dicom.innolitics.com/ciods/ultrasound-image/patient/00100010
#https://dicom.innolitics.com/ciods/ct-image/patient/00100010
#https://dicom.innolitics.com/ciods/nuclear-medicine-image/patient/00100010
#https://dicom.innolitics.com/ciods/computed-radiography-image/patient/00100010
#https://dicom.innolitics.com/ciods/ultrasound-multi-frame-image/patient/00100010
#https://dicom.innolitics.com/ciods/secondary-capture-image/patient/00100010
#https://dicom.innolitics.com/ciods/x-ray-radiofluoroscopic-image/patient/00100010
#https://dicom.innolitics.com/ciods/x-ray-angiographic-image/patient/00100010
#https://dicom.innolitics.com/ciods/rt-image/patient/00100010
#https://dicom.innolitics.com/ciods/positron-emission-tomography-image/patient/00100010
#https://dicom.innolitics.com/ciods/digital-x-ray-image/patient/00100010
#https://dicom.innolitics.com/ciods/vl-endoscopic-image/patient/00100010
#https://dicom.innolitics.com/ciods/video-endoscopic-image/patient/00100010
#https://dicom.innolitics.com/ciods/vl-microscopic-image/patient/00100010
#https://dicom.innolitics.com/ciods/vl-photographic-image/patient/00100010
#https://dicom.innolitics.com/ciods/video-microscopic-image/patient/00100010
#https://dicom.innolitics.com/ciods/video-photographic-image/patient/00100010
#https://dicom.innolitics.com/ciods/dermoscopic-photography-image/patient/00100010
- name: "Patient ID"
  group: 0x0010
  element: 0x0020
  op: "secure-hash"
- name: "Patient's Birth Date"
  group: 0x0010
  element: 0x0030
  op: "replace"
- name: "Patient's Sex"
  group: 0x0010
  element: 0x0040
  op: "keep"
####### 0018 Group #######
- name: "Scan Options Attribute"
  group: 0x0018
  element: 0x0022
  op: "replace"
#https://dicom.innolitics.com/ciods/ct-image/ct-image/00180022
#https://dicom.innolitics.com/ciods/mr-image/mr-image/00180022
#https://dicom.innolitics.com/ciods/x-ray-radiofluoroscopic-image/x-ray-image/00180022
#https://dicom.innolitics.com/ciods/x-ray-angiographic-image/x-ray-image/00180022
#https://dicom.innolitics.com/ciods/enhanced-xrf-image/enhanced-xa-xrf-image/00180022
#https://dicom.innolitics.com/ciods/enhanced-xa-image/enhanced-xa-xrf-image/00180022
- name: "MR Acquisition Type"
  group: 0x0018
  element: 0x0023
  op: "keep"
- name: "Sequence Name"
  group: 0x0018
  element: 0x0024
  op: "keep"
- name: "Repetition Time"
  group: 0x0018
  element: 0x0080
  op: "keep"
- name: "Echo Time"
  group: 0x0018
  element: 0x0081
  op: "keep"
- name: "Inversion Time"
  group: 0x0018
  element: 0x0082
  op: "keep"
- name: "Number of Averages"
  group: 0x0018
  element: 0x0083
  op: "keep"
- name: "Magnetic Field Strength"
  group: 0x0018
  element: 0x0087
  op: "keep"
- name: "Spacing Between Slices"
  group: 0x0018
  element: 0x0088
  op: "keep"
- name: "Echo train length"
  group: 0x0018
  element: 0x0091
  op: "keep"
- name: "Percent Phase Field of View"
  group: 0x0018
  element: 0x0094
  op: "keep"
- name: "Software Version"
  group: 0x0018
  element: 0x1020
  op: "keep"
- name: "Field Of View Dimension"
  group: 0x0018
  element: 0x1149
  op: "keep"
- name: "Imager Pixel Spacing"
  group: 0x0018
  element: 0x1164
  op: "keep"
- name: "Grid"
  group: 0x0018
  element: 0x1166
  op: "keep"
- name: "Focal Spot"
  group: 0x0018
  element: 0x1190
  op: "keep"
- name: "Receive Coil Name"
  group: 0x0018
  element: 0x1250
  op: "keep"
- name: "Transmit Coil Name"
  group: 0x0018
  element: 0x1251
  op: "keep"
- name: "Flip Angle"
  group: 0x0018
  element: 0x1314
  op: "keep"
- name: "SAR"
  group: 0x0018
  element: 0x1316
  op: "keep"
- name: "Acquisition Device Processing Description"
  group: 0x0018
  element: 0x1400
  op: "keep"
- name: "Patient Position"
  group: 0x0018
  element: 0x5100
  op: "replace"
- name: "MR Acquisition Frequency Encoding Steps"
  group: 0x0018
  element: 0x9058
  op: "keep"
- name: "MR Acquisition Phase Encoding Steps in-plane"
  group: 0x0018
  element: 0x9231
  op: "keep"
####### 0020 Group #######
- name: "Study Instance UID"
  group: 0x0020
  element: 0x000d
  op: "replace_UID"
#https://dicom.innolitics.com/ciods/ultrasound-image/general-study/0020000d
#https://dicom.innolitics.com/ciods/mr-image/general-study/0020000d
#https://dicom.innolitics.com/ciods/ct-image/general-study/0020000d
#https://dicom.innolitics.com/ciods/rt-image/general-study/0020000d
#https://dicom.innolitics.com/ciods/photoacoustic-image/general-study/0020000d
#https://dicom.innolitics.com/ciods/enhanced-mr-color-image/enhanced-mr-image/0008113a/0020000d
#NOTE List of searched term continutes
- name: "Series Instance UID"
  group: 0x0020
  element: 0x000e
  op: "replace_UID"
- name: "Study ID"
  group: 0x0020
  element: 0x0010
  op: "replace"
- name: "Series Number"
  group: 0x0020
  element: 0x0011
  op: "keep"
- name: "Acquisition Number"
  group: 0x0020
  element: 0x0012
  op: "keep"
- name: "Instance Number"
  group: 0x0020
  element: 0x0013
  op: "keep"
- name: "Patient Orientation"
  group: 0x0020
  element: 0x0020
  op: "keep"
- name: "Image Position (Patient)"
  group: 0x0020
  element: 0x0032
  op: "keep"
- name: "Image Orientation (Patient)"
  group: 0x0020
  element: 0x0037
  op: "keep"
- name: "Image Laterality"
  group: 0x0020
  element: 0x0062
  op: "keep"
- name: "Frame of Reference UID"
  group: 0x0020
  element: 0x0052
  op: "replace_UID"
- name: "Synchronization Frame of Reference UID"
  group: 0x0020
  element: 0x0200
  op: "replace_UID"
- name: "Position Reference Indicator"
  group: 0x0020
  element: 0x1040
  op: "replace"
####### 0028 Group #######
- name: "Samples Per Pixel"
  group: 0x0028
  element: 0x0002
  op: "keep"
#https://dicom.innolitics.com/ciods/ct-image/image-pixel/00280002
#https://dicom.innolitics.com/ciods/ct-image/ct-image/00280002
#https://dicom.innolitics.com/ciods/mr-image/image-pixel/00280002
#https://dicom.innolitics.com/ciods/mr-image/mr-image/00280002
#https://dicom.innolitics.com/ciods/ultrasound-image/image-pixel/00280002
#https://dicom.innolitics.com/ciods/ultrasound-image/us-image/00280002
#https://dicom.innolitics.com/ciods/rt-image/image-pixel/00280002
#https://dicom.innolitics.com/ciods/rt-image/rt-image/00280002
#NOTE List of searched term continutes
- name: "Photometric Interpretation"
  group: 0x0028
  element: 0x0004
  op: "keep"
- name: "Planar Configuration"
  group: 0x0028
  element: 0x0006
  op: "keep"
- name: "Rows"
  group: 0x0028
  element: 0x0010
  op: "keep"
- name: "Columns"
  group: 0x0028
  element: 0x0011
  op: "keep"
- name: "Pixel Spacing"
  group: 0x0028
  element: 0x0030
  op: "keep"
- name: "Bits Allocated"
  group: 0x0028
  element: 0x0100
  op: "keep"
- name: "Bits Stored"
  group: 0x0028
  element: 0x0101
  op: "keep"
- name: "High Bit"
  group: 0x0028
  element: 0x0102
  op: "keep"
- name: "Pixel Representation"
  group: 0x0028
  element: 0x0103
  op: "keep"
- name: "Burned In Annotation"
  group: 0x0028
  element: 0x0301
  op: "keep"
- name: "LUTDescriptor"
  group: 0x0028
  element: 0x0302
  op: "keep"
- name: "Pixel Spacing Calibration Type"
  group: 0x0028
  element: 0x0a02
  op: "keep"
- name: "Pixel Spacing Calibration Description"
  group: 0x0028
  element: 0x0a04
  op: "keep"
- name: "Pixel Intensity Relationship"
  group: 0x0028
  element: 0x1040
  op: "keep"
- name: "Pixel Intensity Relationship Sign"
  group: 0x0028
  element: 0x1041
  op: "keep"
- name: "Window Center"
  group: 0x0028
  element: 0x1050
  op: "keep"
- name: "Window Width"
  group: 0x0028
  element: 0x1051
  op: "keep"
- name: "Rescale Intercept"
  group: 0x0028
  element: 0x1052
  op: "keep"
- name: "Rescale Slope"
  group: 0x0028
  element: 0x1053
  op: "keep"
- name: "Rescale Type"
  group: 0x0028
  element: 0x1054
  op: "keep"
- name: "Window Center And Width Explanation"
  group: 0x0028
  element: 0x1055
  op: "keep"
- name: "Lossy Image Compression"
  group: 0x0028
  element: 0x2110
  op: "keep"
- name: "VOI LUT Sequence"
  group: 0x0028
  element: 0x3010
  op: "keep"
####### 0040 Group #######
- name: "UID Attribute"
  group: 0x0040
  element: 0xA124
  op: "replace_UID"
#https://dicom.innolitics.com/ciods/ct-image/specimen/00400560/00400620/0040a124
#https://dicom.innolitics.com/ciods/mr-image/specimen/00400560/00400620/0040a124
#https://dicom.innolitics.com/ciods/ultrasound-image/specimen/00400560/00400620/0040a124
#https://dicom.innolitics.com/ciods/photoacoustic-image/specimen/00400560/00400620/0040a124
#https://dicom.innolitics.com/ciods/ct-image/general-image/00409096/00409220/0040a124
#https://dicom.innolitics.com/ciods/nuclear-medicine-image/general-image/00409096/00409220/00400441/0040a124
#NOTE List of searched term continutes
- name: "Real World Value Intercept"
  group: 0x0040
  element: 0x9924
  op: "replace_UID"
- name: "Real World Value Slope"
  group: 0x0040
  element: 0x9925
  op: "replace_UID"
####### 0054 Group #######
- name: "View Code Sequence"
  group: 0x0054
  element: 0x0220
  op: "keep"
#https://dicom.innolitics.com/ciods/ct-image/ct-image/00540220
#https://dicom.innolitics.com/ciods/mr-image/mr-image/00540220
#https://dicom.innolitics.com/ciods/ultrasound-image/us-image/00540220
#https://dicom.innolitics.com/ciods/ultrasound-multi-frame-image/us-image/00540220
#https://dicom.innolitics.com/ciods/multi-frame-single-bit-secondary-capture-image/sc-image/00540220
#NOTE List of searched term continutes
####### 0088 Group #######
- name: "Storage Media File-set UID"
  group: 0x0088
  element: 0x0140
  op: "replace_UID"
# NOTE: not found!
####### 3006 Group #######
- name: "Referenced Frame of Reference UID"
  group: 0x3006
  element: 0x0024
  op: "replace_UID"
#https://dicom.innolitics.com/ciods/rt-structure-set/structure-set/30060020/30060024
# NOTE: dont' see image modalities
- name: "Related Frame of Reference UID"
  group: 0x3006
  element: 0x00C2
  op: "replace_UID"
####### 7FE0 Group #######
- name: "Pixel Data"
  group: 0x7fe0
  element: 0x0010
  op: "keep"
#https://dicom.innolitics.com/ciods/computed-radiography-image/image-pixel/7fe00010
#https://dicom.innolitics.com/ciods/ct-image/general-image/00880200/7fe00010
#https://dicom.innolitics.com/ciods/ultrasound-image/general-image/00880200/7fe00010
#https://dicom.innolitics.com/ciods/nuclear-medicine-image/image-pixel/7fe00010
#https://dicom.innolitics.com/ciods/secondary-capture-image/image-pixel/7fe00010
#https://dicom.innolitics.com/ciods/rt-image/image-pixel/7fe00010
#NOTE List of searched term continutes
