#  Copyright (c) University College London Hospitals NHS Foundation Trust
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Specific tag operations for spectroscopy data projects

#################################### 0002 Group ###################################
#
#
- name: "File Meta Information Group Length"
  group: 0x0002
  element: 0x0000
  op: "keep"
- name: "File Meta Information Version"
  group: 0x0002
  element: 0x0001
  op: "keep"
- name: "Media Storage SOP Class UID"
  group: 0x0002
  element: 0x0002
  op: "keep"
- name: "Media Storage SOP Instance UID"
  group: 0x0002
  element: 0x0003
  op: "keep"
- name: "Transfer Syntax UID"
  group: 0x0002
  element: 0x0010
  op: "keep"
- name: "Implementation Class UID"
  group: 0x0002
  element: 0x0012
  op: "keep"
- name: "Implementation Version Name"
  group: 0x0002
  element: 0x0013
  op: "keep"
#################################### 0008 Group ###################################
#
#
- name: "Specific Character Set"
  group: 0x0008
  element: 0x0005
  op: "keep"
- name: "Image Type"
  group: 0x0008
  element: 0x0008
  op: "keep"
- name: "SOP Class UID"
  group: 0x0008
  element: 0x0016
  op: "keep"
- name: "SOP Instance UID"
  group: 0x0008
  element: 0x0018
  op: "keep"
- name: "Study Date"
  group: 0x0008
  element: 0x0020
  op: "keep"
- name: "Series Date"
  group: 0x0008
  element: 0x0021
  op: "keep"
- name: "Content Date"
  group: 0x0008
  element: 0x0023
  op: "keep"
- name: "Acquisition DateTime"
  group: 0x0008
  element: 0x002a
  op: "keep"
- name: "Study Time"
  group: 0x0008
  element: 0x0030
  op: "keep"
- name: "Series Time"
  group: 0x0008
  element: 0x0031
  op: "keep"
- name: "Content Time"
  group: 0x0008
  element: 0x0033
  op: "keep"
- name: "Accession Number"
  group: 0x0008
  element: 0x0050
  op: "keep"
- name: "Modality"
  group: 0x0008
  element: 0x0060
  op: "keep"
- name: "Manufacturer"
  group: 0x0008
  element: 0x0070
  op: "keep"
- name: "Institution Name"
  group: 0x0008
  element: 0x0080
  op: "keep"
- name: "Institution Address"
  group: 0x0008
  element: 0x0081
  op: "keep"
- name: "Referring Physician's Name"
  group: 0x0008
  element: 0x0090
  op: "keep"
- name: "Station Name"
  group: 0x0008
  element: 0x1010
  op: "keep"
- name: "Study Description"
  group: 0x0008
  element: 0x1030
  op: "keep"
- name: "Series Description"
  group: 0x0008
  element: 0x103e
  op: "keep"
- name: "Operators' Name"
  group: 0x0008
  element: 0x1070
  op: "keep"
- name: "Admitting Diagnoses Description"
  group: 0x0008
  element: 0x1080
  op: "keep"
- name: "Manufacturer's Model Name"
  group: 0x0008
  element: 0x1090
  op: "keep"
- name: "Referenced Performed Procedure Step Sequence"
  group: 0x0008
  element: 0x1111
  op: "keep"
- name: "Referenced SOP Class UID"
  group: 0x0008
  element: 0x1150
  op: "keep"
- name: "Referenced SOP Instance UID"
  group: 0x0008
  element: 0x1155
  op: "keep"
- name: "Volumetric Properties"
  group: 0x0008
  element: 0x9206
  op: "keep"
- name: "Volume Based Calculation Technique"
  group: 0x0008
  element: 0x9207
  op: "keep"
- name: "Complex Image Component"
  group: 0x0008
  element: 0x9208
  op: "keep"
- name: "Acquisition Contrast"
  group: 0x0008
  element: 0x9209
  op: "keep"
#################################### 0018 Group ###################################
#
#
- name: "RF Echo Train Length Attribute"
  group: 0x0018
  element: 0x9240
  op: "keep"
#https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009230/00189112/00189240
- name: "MR Timing and Related Parameters Sequence Attribute"
  group: 0x0018
  element: 0x9112
  op: "keep"
#https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009230/00189112

#################################### Default Tags in DICOM/csi_slaser_40_20_MR/1.dcm ###################################
#
# Let me add tags that are present in the default DICOM file
#
# (0009, 0010) Private Creator
# (0009, 108c) Private tag data
# (0010, 0010) Patient's Name
# (0010, 0020) Patient ID
# (0010, 0021) Issuer of Patient ID
# (0010, 0030) Patient's Birth Date
# (0010, 0040) Patient's Sex
# (0010, 1010) Patient's Age
# (0010, 1020) Patient's Size
# (0010, 1030) Patient's Weight
# (0010, 2000) Medical Alerts
# (0010, 2110) Allergies
# (0018, 0015) Body Part Examined
# (0018, 0087) Magnetic Field Strength
# (0018, 1000) Device Serial Number
# (0018, 1020) Software Versions
# (0018, 1030) Protocol Name
# (0018, 1050) Spatial Resolution
# (0018, 1200) Date of Last Calibration
# (0018, 1201) Time of Last Calibration
# (0018, 1320) B1rms
# (0018, 5100) Patient Position
# (0018, 9004) Content Qualification
# (0018, 9005) Pulse Sequence Name
# (0018, 9008) Echo Pulse Sequence
# (0018, 9011) Multiple Spin Echo
# (0018, 9012) Multi-planar Excitation
# (0018, 9017) Steady State Pulse Sequence
# (0018, 9018) Echo Planar Pulse Sequence
# (0018, 9025) Spectrally Selected Suppression
# (0018, 9032) Geometry of k-Space Traversal
# (0018, 9033) Segmented k-Space Traversal
# (0018, 9034) Rectilinear Phase Encode Reordering
# (0018, 9052) Spectral Width
# (0018, 9053) Chemical Shift Reference
# (0018, 9054) Volume Localization Technique
# (0018, 9059) De-coupling
# (0018, 9064) k-space Filtering
# (0018, 9065) Time Domain Filtering
# (0018, 9066) Number of Zero Fills
# (0018, 9067) Baseline Correction
# (0018, 9073) Acquisition Duration
# (0018, 9093) Number of k-Space Trajectories
# (0018, 9098) Transmitter Frequency
# (0018, 9100) Resonant Nucleus
# (0018, 9101) Frequency Correction
# (0018, 9126)  Volume Localization Sequence  3 item(s) ----
#    (0018, 9104) Slab Thickness
#    (0018, 9105) Slab Orientation
#    (0018, 9106) Mid Slab Position
#    (0018, 9104) Slab Thickness
#    (0018, 9105) Slab Orientation
#    (0018, 9106) Mid Slab Position
#    (0018, 9104) Slab Thickness
#    (0018, 9105) Slab Orientation
#    (0018, 9106) Mid Slab Position
# (0018, 9174) Applicable Safety Standard Agency
# (0018, 9198) First Order Phase Correction
# (0018, 9199) Water Referenced Phase Correction
# (0018, 9200) MR Spectroscopy Acquisition Type
#
#
# (0020, 000d) Study Instance UID
# (0020, 000e) Series Instance UID
# (0020, 0010) Study ID
# (0020, 0011) Series Number
# (0020, 0012) Acquisition Number
# (0020, 0013) Instance Number
# (0020, 0052) Frame of Reference UID
# (0020, 1040) Position Reference Indicator
# (0020, 4000) Image Comments
# (0020, 9221)  Dimension Organization Sequence  1 item(s) ----
#    (0020, 9164) Dimension Organization UID
# (0020, 9222)  Dimension Index Sequence
#    (0020, 9164) Dimension Organization UID
#    (0020, 9165) Dimension Index Pointer
#    (0020, 9167) Functional Group Pointer
#    (0020, 9164) Dimension Organization UID
#    (0020, 9165) Dimension Index Pointer
#    (0020, 9167) Functional Group Pointer
#    (0020, 9164) Dimension Organization UID
#    (0020, 9165) Dimension Index Pointer
#    (0020, 9167) Functional Group Pointer
#
# ...
# The list continues to to line 625 in the original file
#