#  Copyright (c) University College London Hospitals NHS Foundation Trust
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

- name: Device Serial Number
  group: 0x0018
  element: 0x1000
  op: keep
- name: Content Qualification
  group: 0x0018
  element: 0x9004
  op: keep
- name: Pulse Sequence Name
  group: 0x0018
  element: 0x9005
  op: keep
- name: Echo Pulse Sequence
  group: 0x0018
  element: 0x9008
  op: keep
- name: Multi-planar Excitation
  group: 0x0018
  element: 0x9012
  op: keep
- name: Steady State Pulse Sequence
  group: 0x0018
  element: 0x9017
  op: keep
- name: Echo Planar Pulse Sequence
  group: 0x0018
  element: 0x9018
  op: keep
- name: Spectrally Selected Suppression
  group: 0x0018
  element: 0x9025
  op: keep
- name: Geometry of k-Space Traversal
  group: 0x0018
  element: 0x9032
  op: keep
- name: Segmented k-Space Traversal
  group: 0x0018
  element: 0x9033
  op: keep
- name: Spectral Width
  group: 0x0018
  element: 0x9052
  op: keep
- name: Chemical Shift Reference
  group: 0x0018
  element: 0x9053
  op: keep
- name: Volume Localization Technique
  group: 0x0018
  element: 0x9054
  op: keep
- name: De-coupling
  group: 0x0018
  element: 0x9059
  op: keep
- name: k-space Filtering
  group: 0x0018
  element: 0x9064
  op: keep
- name: Time Domain Filtering
  group: 0x0018
  element: 0x9065
  op: keep
- name: Number of Zero Fills
  group: 0x0018
  element: 0x9066
  op: keep
- name: Baseline Correction
  group: 0x0018
  element: 0x9067
  op: keep
- name: Acquisition Duration
  group: 0x0018
  element: 0x9073
  op: keep
- name: Number of k-Space Trajectories
  group: 0x0018
  element: 0x9093
  op: keep
- name: Transmitter Frequency
  group: 0x0018
  element: 0x9098
  op: keep
- name: Resonant Nucleus
  group: 0x0018
  element: 0x9100
  op: keep
- name: Frequency Correction
  group: 0x0018
  element: 0x9101
  op: keep
- name: Slab Thickness
  group: 0x0018
  element: 0x9104
  op: keep
- name: Slab Orientation
  group: 0x0018
  element: 0x9105
  op: keep
- name: Mid Slab Position
  group: 0x0018
  element: 0x9106
  op: keep
- name: Multiple Spin Echo
  group: 0x0018
  element: 0x9011
  op: keep
- name: Volume Localization Sequence
  group: 0x0018
  element: 0x9126
  op: keep
- name: Applicable Safety Standard Agency
  group: 0x0018
  element: 0x9174
  op: keep
- name: First Order Phase Correction
  group: 0x0018
  element: 0x9198
  op: keep
- name: Water Referenced Phase Correction
  group: 0x0018
  element: 0x9199
  op: keep
- name: MR Spectroscopy Acquisition Type
  group: 0x0018
  element: 0x9200
  op: keep
- name: Dimension Organization UID
  group: 0x0020
  element: 0x9164
  op: keep
- name: Dimension Index Pointer
  group: 0x0020
  element: 0x9165
  op: keep
- name: Dimension Organization Sequence
  group: 0x0020
  element: 0x9221
  op: keep
- name: Dimension Index Sequence
  group: 0x0020
  element: 0x9222
  op: keep
- name: Number of Frames
  group: 0x0028
  element: 0x0008
  op: keep
- name: Data Point Rows
  group: 0x0028
  element: 0x9001
  op: keep
- name: Data Point Columns
  group: 0x0028
  element: 0x9002
  op: keep
- name: Signal Domain Columns
  group: 0x0028
  element: 0x9003
  op: keep
- name: Data Representation
  group: 0x0028
  element: 0x9108
  op: keep
- name: Acquisition Context Sequence
  group: 0x0040
  element: 0x0555
  op: keep
- name: Shared Functional Groups Sequence
  group: 0x5200
  element: 0x9229
  op: keep
- name: Spectroscopy Data
  group: 0x5600
  element: 0x0020
  op: keep
