#  Copyright (c) University College London Hospitals NHS Foundation Trust
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Default configuration for Standard MR Image

- name: "Private Creator Data Element"
  group: 0x000d
  element: 0x0010
  op: "keep"
- name: "UCLH Project Name"
  group: 0x000d
  element: 0x1001
  op: "keep"
- name: "Specific Character Set"
  group: 0x0008
  element: 0x0005
  op: "keep"
- name: "Image Type"
  group: 0x0008
  element: 0x0008
  op: "keep"
- name: "Instance Creator UID"
  group: 0x0008
  element: 0x0014
  op: "replace_UID"
- name: "SOP Class UID"
  group: 0x0008
  element: 0x0016
  op: "keep"
- name: "SOP Instance UID"
  group: 0x0008
  element: 0x0018
  op: "replace_UID"
- name: "Accession Number"
  group: 0x0008
  element: 0x0050
  op: "replace"
- name: "Study Date"
  group: 0x0008
  element: 0x0020
  op: "replace"
- name: "General Study"
  group: 0x0008
  element: 0x0030
  op: "replace"
- name: "Modality"
  group: 0x0008
  element: 0x0060
  op: "keep"
- name: "Modalities In Study"
  group: 0x0008
  element: 0x0061
  op: "keep"
- name: "Manufacturer"
  group: 0x0008
  element: 0x0070
  op: "keep"
- name: "Referring Physician's Name"
  group: 0x0008
  element: 0x0090
  op: "replace"
- name: "Study Description"
  group: 0x0008
  element: 0x1030
  op: "keep"
- name: "Series Description"
  group: 0x0008
  element: 0x103e
  op: "keep"
- name: "Manufacturers Model Name"
  group: 0x0008
  element: 0x1090
  op: "keep"
- name: "Referenced Series Sequence"
  group: 0x0008
  element: 0x1155
  op: "replace_UID"
- name: "Referenced Frame Number"
  group: 0x0008
  element: 0x1160
  op: "keep"
- name: "Pixel Presentation"
  group: 0x0008
  element: 0x9205
  op: "keep"
- name: "Volumetric Properties"
  group: 0x0008
  element: 0x9206
  op: "keep"
- name: "Volume Based Calculation Technique"
  group: 0x0008
  element: 0x9207
  op: "keep"
- name: "Complex Image Component"
  group: 0x0008
  element: 0x9208
  op: "keep"
- name: "Acquisition Contrast"
  group: 0x0008
  element: 0x9209
  op: "keep"
- name: "Patients Name"
  group: 0x0010
  element: 0x0010
  op: "replace"
- name: "Patient ID"
  group: 0x0010
  element: 0x0020
  op: "secure-hash"
- name: "Patient's Birth Date"
  group: 0x0010
  element: 0x0030
  op: "replace"
- name: "Patient's Sex"
  group: 0x0010
  element: 0x0040
  op: "keep"
- name: "Scanning Sequence"
  group: 0x0018
  element: 0x0020
  op: "keep"
- name: "Sequence Variant"
  group: 0x0018
  element: 0x0021
  op: "keep"
- name: "MR Image"
  group: 0x0018
  element: 0x0022
  op: "replace"
- name: "MR Acquisition Type"
  group: 0x0018
  element: 0x0023
  op: "keep"
- name: "Sequence Name"
  group: 0x0018
  element: 0x0024
  op: "keep"
- name: "Slice Thickness"
  group: 0x0018
  element: 0x0050
  op: "keep"
- name: "Repetition Time"
  group: 0x0018
  element: 0x0080
  op: "keep"
- name: "Echo Time"
  group: 0x0018
  element: 0x0081
  op: "keep"
- name: "Inversion Time"
  group: 0x0018
  element: 0x0082
  op: "keep"
- name: "Number of Averages"
  group: 0x0018
  element: 0x0083
  op: "keep"
- name: "Magnetic Field Strength"
  group: 0x0018
  element: 0x0087
  op: "keep"
- name: "Spacing Between Slices"
  group: 0x0018
  element: 0x0088
  op: "keep"
- name: "Echo train length"
  group: 0x0018
  element: 0x0091
  op: "keep"
- name: "Percent Phase Field of View"
  group: 0x0018
  element: 0x0094
  op: "keep"
- name: "Software Version"
  group: 0x0018
  element: 0x1020
  op: "keep"
- name: "Protocol Name"
  group: 0x0018
  element: 0x1030
  op: "delete"
- name: "Field Of View Dimension"
  group: 0x0018
  element: 0x1149
  op: "keep"
- name: "Imager Pixel Spacing"
  group: 0x0018
  element: 0x1164
  op: "keep"
- name: "Grid"
  group: 0x0018
  element: 0x1166
  op: "keep"
- name: "Focal Spot"
  group: 0x0018
  element: 0x1190
  op: "keep"
- name: "Receive Coil Name"
  group: 0x0018
  element: 0x1250
  op: "keep"
- name: "Transmit Coil Name"
  group: 0x0018
  element: 0x1251
  op: "keep"
- name: "Flip Angle"
  group: 0x0018
  element: 0x1314
  op: "keep"
- name: "SAR"
  group: 0x0018
  element: 0x1316
  op: "keep"
- name: "Acquisition Device Processing Description"
  group: 0x0018
  element: 0x1400
  op: "keep"
- name: "Patient Position"
  group: 0x0018
  element: 0x5100
  op: "replace"
- name: "MR Acquisition Frequency Encoding Steps"
  group: 0x0018
  element: 0x9058
  op: "keep"
- name: "MR Acquisition Phase Encoding Steps in-plane"
  group: 0x0018
  element: 0x9231
  op: "keep"
- name: "Study Instance UID"
  group: 0x0020
  element: 0x000d
  op: "replace_UID"
- name: "Series Instance UID"
  group: 0x0020
  element: 0x000e
  op: "replace_UID"
- name: "Study ID"
  group: 0x0020
  element: 0x0010
  op: "replace"
- name: "Series Number"
  group: 0x0020
  element: 0x0011
  op: "keep"
- name: "Acquisition Number"
  group: 0x0020
  element: 0x0012
  op: "keep"
- name: "Instance Number"
  group: 0x0020
  element: 0x0013
  op: "keep"
- name: "Patient Orientation"
  group: 0x0020
  element: 0x0020
  op: "keep"
- name: "Image Position (Patient)"
  group: 0x0020
  element: 0x0032
  op: "keep"
- name: "Image Orientation (Patient)"
  group: 0x0020
  element: 0x0037
  op: "keep"
- name: "Image Laterality"
  group: 0x0020
  element: 0x0062
  op: "keep"
- name: "Frame of Reference UID"
  group: 0x0020
  element: 0x0052
  op: "replace_UID"
- name: "Synchronization Frame of Reference UID"
  group: 0x0020
  element: 0x0200
  op: "replace_UID"
- name: "Position Reference Indicator"
  group: 0x0020
  element: 0x1040
  op: "replace"
- name: "Samples Per Pixel"
  group: 0x0028
  element: 0x0002
  op: "keep"
- name: "Photometric Interpretation"
  group: 0x0028
  element: 0x0004
  op: "keep"
- name: "Planar Configuration"
  group: 0x0028
  element: 0x0006
  op: "keep"
- name: "Rows"
  group: 0x0028
  element: 0x0010
  op: "keep"
- name: "Columns"
  group: 0x0028
  element: 0x0011
  op: "keep"
- name: "Pixel Spacing"
  group: 0x0028
  element: 0x0030
  op: "keep"
- name: "Bits Allocated"
  group: 0x0028
  element: 0x0100
  op: "keep"
- name: "Bits Stored"
  group: 0x0028
  element: 0x0101
  op: "keep"
- name: "High Bit"
  group: 0x0028
  element: 0x0102
  op: "keep"
- name: "Pixel Representation"
  group: 0x0028
  element: 0x0103
  op: "keep"
- name: "Burned In Annotation"
  group: 0x0028
  element: 0x0301
  op: "keep"
- name: "LUTDescriptor"
  group: 0x0028
  element: 0x0302
  op: "keep"
- name: "Pixel Spacing Calibration Type"
  group: 0x0028
  element: 0x0a02
  op: "keep"
- name: "Pixel Spacing Calibration Description"
  group: 0x0028
  element: 0x0a04
  op: "keep"
- name: "Pixel Intensity Relationship"
  group: 0x0028
  element: 0x1040
  op: "keep"
- name: "Pixel Intensity Relationship Sign"
  group: 0x0028
  element: 0x1041
  op: "keep"
- name: "Window Center"
  group: 0x0028
  element: 0x1050
  op: "keep"
- name: "Window Width"
  group: 0x0028
  element: 0x1051
  op: "keep"
- name: "Rescale Intercept"
  group: 0x0028
  element: 0x1052
  op: "keep"
- name: "Rescale Slope"
  group: 0x0028
  element: 0x1053
  op: "keep"
- name: "Rescale Type"
  group: 0x0028
  element: 0x1054
  op: "keep"
- name: "Window Center And Width Explanation"
  group: 0x0028
  element: 0x1055
  op: "keep"
- name: "Lossy Image Compression"
  group: 0x0028
  element: 0x2110
  op: "keep"
- name: "VOI LUT Sequence"
  group: 0x0028
  element: 0x3010
  op: "keep"
- name: "Current Patient Location"
  group: 0x0038
  element: 0x0300
  op: "delete"
- name: "UID"
  group: 0x0040
  element: 0xA124
  op: "replace_UID"
- name: "Real World Value Intercept"
  group: 0x0040
  element: 0x9924
  op: "replace_UID"
- name: "Real World Value Slope"
  group: 0x0040
  element: 0x9925
  op: "replace_UID"
- name: "View Code Sequence"
  group: 0x0054
  element: 0x0220
  op: "keep"
- name: "Storage Media File-set UID"
  group: 0x0088
  element: 0x0140
  op: "replace_UID"
- name: "Referenced Frame of Reference UID"
  group: 0x3006
  element: 0x0024
  op: "replace_UID"
- name: "Related Frame of Reference UID"
  group: 0x3006
  element: 0x00C2
  op: "replace_UID"
- name: "Pixel Data"
  group: 0x7fe0
  element: 0x0010
  op: "keep"
