#  Copyright (c) University College London Hospitals NHS Foundation Trust
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Default configuration for Standard MR Image with commented links of resepctive tags
# See further details at:
# https://dicom.innolitics.com/ciods/mr-image
# https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.4.3.html#table_A.4-1

################################### 0008 Group ###################################
#
#
- name: "Volumetric Properties"
  group: 0x0008
  element: 0x9206
  op: "keep"
- name: "Volume Based Calculation Technique"
  group: 0x0008
  element: 0x9207
  op: "keep"
- name: "Complex Image Component"
  group: 0x0008
  element: 0x9208
  op: "keep"
- name: "Acquisition Contrast"
  group: 0x0008
  element: 0x9209
  op: "keep"
#################################### 0018 Group ###################################
#
#
- name: "Scanning Sequence"
  group: 0x0018
  element: 0x0020
  op: "keep"
- name: "Sequence Variant"
  group: 0x0018
  element: 0x0021
  op: "keep"
- name: "MR Acquisition Type"
  group: 0x0018
  element: 0x0023
  op: "keep"
#https://dicom.innolitics.com/ciods/mr-image/mr-image/00180023
#https://dicom.innolitics.com/ciods/enhanced-mr-image/mr-pulse-sequence/00180023
#https://dicom.innolitics.com/ciods/enhanced-mr-color-image/mr-pulse-sequence/00180023
- name: "Sequence Name"
  group: 0x0018
  element: 0x0024
  op: "keep"
- name: "Slice Thickness"
  group: 0x0018
  element: 0x0050
  op: "keep"
- name: "Repetition Time"
  group: 0x0018
  element: 0x0080
  op: "keep"
#https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009229/00189112/00180080
#https://dicom.innolitics.com/ciods/enhanced-mr-color-image/enhanced-mr-color-image-multi-frame-functional-groups/52009229/00189112/00180080
- name: "Echo Time"
  group: 0x0018
  element: 0x0081
  op: "keep"
- name: "Inversion Time"
  group: 0x0018
  element: 0x0082
  op: "keep"
- name: "Number of Averages"
  group: 0x0018
  element: 0x0083
  op: "keep"
#https://dicom.innolitics.com/ciods/mr-image/mr-image/00180083
#https://dicom.innolitics.com/ciods/mr-spectroscopy/mr-spectroscopy-multi-frame-functional-groups/52009229/00189119/00180083
#https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009230/00189119/00180083
#https://dicom.innolitics.com/ciods/enhanced-mr-color-image/enhanced-mr-color-image-multi-frame-functional-groups/52009229/00189119/00180083
- name: "Magnetic Field Strength"
  group: 0x0018
  element: 0x0087
  op: "keep"
#https://dicom.innolitics.com/ciods/mr-image/mr-image/00180087
#https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image/00180087
#https://dicom.innolitics.com/ciods/enhanced-mr-color-image/enhanced-mr-image/00180087
#https://dicom.innolitics.com/ciods/legacy-converted-enhanced-mr-image/enhanced-mr-image/00180087
- name: "Spacing Between Slices"
  group: 0x0018
  element: 0x0088
  op: "keep"
#https://dicom.innolitics.com/ciods/ct-image/image-plane/00180088
#https://dicom.innolitics.com/ciods/mr-image/image-plane/00180088
#https://dicom.innolitics.com/ciods/x-ray-3d-angiographic-image/x-ray-3d-angiographic-image-multi-frame-functional-groups/52009229/00289110/00180088
#https://dicom.innolitics.com/ciods/x-ray-3d-craniofacial-image/x-ray-3d-craniofacial-image-multi-frame-functional-groups/52009229/00289110/00180088
- name: "Echo train length"
  group: 0x0018
  element: 0x0091
  op: "keep"
#https://dicom.innolitics.com/ciods/mr-image/mr-image/00180091
#https://dicom.innolitics.com/ciods/mr-spectroscopy/mr-spectroscopy-multi-frame-functional-groups/52009229/00189112/00180091
#https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009229/00189112/00180091
#https://dicom.innolitics.com/ciods/enhanced-mr-color-image/enhanced-mr-color-image-multi-frame-functional-groups/52009229/00189112/00180091
- name: "Percent Phase Field of View"
  group: 0x0018
  element: 0x0094
  op: "keep"
#https://dicom.innolitics.com/ciods/mr-image/mr-image/00180094
#https://dicom.innolitics.com/ciods/mr-spectroscopy/mr-spectroscopy-multi-frame-functional-groups/52009229/00189103/00180094
#https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009229/00189125/00180094
#https://dicom.innolitics.com/ciods/enhanced-mr-color-image/enhanced-mr-color-image-multi-frame-functional-groups/52009229/00189125/00180094
- name: "Field Of View Dimension"
  group: 0x0018
  element: 0x1149
  op: "keep"
- name: "Imager Pixel Spacing"
  group: 0x0018
  element: 0x1164
  op: "keep"
- name: "Grid"
  group: 0x0018
  element: 0x1166
  op: "keep"
- name: "Receive Coil Name"
  group: 0x0018
  element: 0x1250
  op: "keep"
#https://dicom.innolitics.com/ciods/mr-image/mr-image/00181250
#https://dicom.innolitics.com/ciods/mr-spectroscopy/mr-spectroscopy-multi-frame-functional-groups/52009229/00189042/00181250
#https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009230/00189042/00181250
#https://dicom.innolitics.com/ciods/enhanced-mr-color-image/enhanced-mr-color-image-multi-frame-functional-groups/52009229/00189042/00181250
- name: "Transmit Coil Name"
  group: 0x0018
  element: 0x1251
  op: "keep"
#https://dicom.innolitics.com/ciods/mr-image/mr-image/00181251
#https://dicom.innolitics.com/ciods/mr-spectroscopy/mr-spectroscopy-multi-frame-functional-groups/52009229/00189049/00181251
#https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009230/00189049/00181251
#https://dicom.innolitics.com/ciods/enhanced-mr-color-image/enhanced-mr-color-image-multi-frame-functional-groups/52009229/00189049/00181251
- name: "Flip Angle"
  group: 0x0018
  element: 0x1314
  op: "keep"
#https://dicom.innolitics.com/ciods/mr-image/mr-image/00181314
#https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009230/00189112/00181314
#https://dicom.innolitics.com/ciods/enhanced-mr-color-image/enhanced-mr-color-image-multi-frame-functional-groups/52009229/00189112/00181314
- name: "MR Acquisition Frequency Encoding Steps"
  group: 0x0018
  element: 0x9058
  op: "keep"
#https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009230/00189125/00189058
#https://dicom.innolitics.com/ciods/enhanced-mr-color-image/enhanced-mr-color-image-multi-frame-functional-groups/52009229/00189125/00189058
- name: "MR Acquisition Phase Encoding Steps in-plane"
  group: 0x0018
  element: 0x9231
  op: "keep"
