---
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--settings-path", "setup.cfg"]

  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      args: ["--config", "setup.cfg"]
      exclude: "tests|orthanc"

  - repo: local
    hooks:
      - id: mypy  # This does not work with the official mypy hook
        name: mypy
        language: python
        pass_filenames: false
        entry: mypy
        args: ['--config-file=setup.cfg']
        additional_dependencies: ['mypy', 'types-PyYAML', 'types-requests']
