version: "3.8"

################################################################################
# Common

x-http-proxy: &http-proxy ${HTTP_PROXY}
x-https-proxy: &https-proxy ${HTTPS_PROXY}
x-no-proxy: &no-proxy localhost,127.0.0.1,uclvlddpragae07,hasher-api,orthanc-raw
x-proxy-common: &proxy-common
  HTTP_PROXY: *http-proxy
  http_proxy: *http-proxy
  HTTPS_PROXY: *https-proxy
  https_proxy: *https-proxy
  NO_PROXY: *no-proxy
  no_proxy: *no-proxy

x-build-args-common: &build-args-common
  <<: *proxy-common

x-pixl-common-env: &pixl-common-env
  ENV: ${ENV}
  DEBUG: ${DEBUG}

x-emap-db: &emap-db
  EMAP_UDS_HOST: ${EMAP_UDS_HOST}
  EMAP_UDS_PORT: ${EMAP_UDS_PORT}
  EMAP_UDS_NAME: ${EMAP_UDS_NAME}
  EMAP_UDS_USER: ${EMAP_UDS_USER}
  EMAP_UDS_PASSWORD: ${EMAP_UDS_PASSWORD}

x-logs-volume: &logs-volume
  type: volume
  source: logs
  target: /logs

volumes:
  logs:
  orthanc-anon-data:
  orthanc-raw-data:
  postgres-data:

networks:
  pixl-net:

################################################################################
# Services
services:

  hasher-api:
    build:
      context: .
      dockerfile: ./docker/hasher-api/Dockerfile
      args:
        <<: *build-args-common
    environment:
      <<: *proxy-common
      <<: *pixl-common-env
      AZURE_CLIENT_ID: ${HASHER_API_AZ_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${HASHER_API_AZ_CLIENT_PASSWORD}
      AZURE_TENANT_ID: ${HASHER_API_AZ_TENANT_ID}
      AZURE_KEY_VAULT_NAME: ${HASHER_API_AZ_KEY_VAULT_NAME}
      AZURE_KEY_VAULT_SECRET_NAME: ${HASHER_API_AZ_KEY_VAULT_SECRET_NAME}
    env_file:
      - ./docker/common.env
    ports:
      - "${HASHER_API_PORT}:8000"
    volumes:
      - *logs-volume
    networks:
      - pixl-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://hasher-api:8000/heart-beat" ]
      interval: 10s
      timeout: 30s
      retries: 5
    restart: "no"

  orthanc-anon:
    build:
      context: .
      dockerfile: ./docker/orthanc-anon/Dockerfile
      args:
        <<: *build-args-common
    command: /run/secrets
    environment:
      ORTHANC_NAME: "PIXL: Anon"
      ORTHANC_USERNAME: ${ORTHANC_ANON_USERNAME}
      ORTHANC_PASSWORD: ${ORTHANC_ANON_PASSWORD}
      ORTHANC_ANON_AE_TITLE: ${ORTHANC_ANON_AE_TITLE}
      ORTHANC_RAW_AE_TITLE: ${ORTHANC_RAW_AE_TITLE}
      ORTHANC_RAW_DICOM_PORT: "4242"
      ORTHANC_RAW_HOSTNAME: "orthanc-raw"
      DICOM_WEB_PLUGIN_ENABLED: ${ENABLE_DICOM_WEB}
      HASHER_API_AZ_NAME: ${HASHER_API_AZ_NAME}
      HASHER_API_PORT: 8000
      HTTP_TIMEOUT: ${ORTHANC_ANON_HTTP_TIMEOUT}
      AZ_DICOM_ENDPOINT_NAME: ${AZ_DICOM_ENDPOINT_NAME}
      AZ_DICOM_ENDPOINT_URL: ${AZ_DICOM_ENDPOINT_URL}
      AZ_DICOM_ENDPOINT_TOKEN: ${AZ_DICOM_ENDPOINT_TOKEN}
      AZ_DICOM_ENDPOINT_CLIENT_ID: ${AZ_DICOM_ENDPOINT_CLIENT_ID}
      AZ_DICOM_ENDPOINT_CLIENT_SECRET: ${AZ_DICOM_ENDPOINT_CLIENT_SECRET}
      AZ_DICOM_ENDPOINT_TENANT_ID: ${AZ_DICOM_ENDPOINT_TENANT_ID}
      AZ_DICOM_TOKEN_REFRESH_SECS: "60"
      <<: *proxy-common
      <<: *pixl-common-env
    ports:
      - "${ORTHANC_ANON_DICOM_PORT}:4242"
      - "${ORTHANC_ANON_WEB_PORT}:8042"
    volumes:
      - type: volume
        source: orthanc-anon-data
        target: /var/lib/orthanc/db
      - ${PWD}/orthanc/orthanc-anon/config:/run/secrets:ro
    networks:
      - pixl-net
    restart: "no"

  orthanc-raw:
    build:
      context: .
      dockerfile: ./docker/orthanc-raw/Dockerfile
      args:
        <<: *build-args-common
    command: /run/secrets
    environment:
      ORTHANC_NAME: "PIXL: Raw"
      ORTHANC_USERNAME: ${ORTHANC_RAW_USERNAME}
      ORTHANC_PASSWORD: ${ORTHANC_RAW_PASSWORD}
      ORTHANC_RAW_AE_TITLE: ${ORTHANC_RAW_AE_TITLE}
      VNA_AE_TITLE : ${VNA_AE_TITLE}
      VNA_DICOM_PORT: ${VNA_DICOM_PORT}
      VNA_IP_ADDR: ${VNAQR_IP_ADDR}
      VNAQR_AE_TITLE : ${VNAQR_AE_TITLE}
      VNAQR_DICOM_PORT: ${VNAQR_DICOM_PORT}
      VNAQR_IP_ADDR: ${VNA_IP_ADDR}
      ORTHANC_ANON_AE_TITLE: ${ORTHANC_ANON_AE_TITLE}
      ORTHANC_ANON_DICOM_PORT: "4242"
      ORTHANC_ANON_HOSTNAME: "orthanc-anon"
      PIXL_DB_HOST: "${PIXL_DB_HOST}"
      PIXL_DB_PORT: "${PIXL_DB_PORT}"
      PIXL_DB_USER: "${PIXL_DB_USER}"
      PIXL_DB_PASSWORD: "${PIXL_DB_PASSWORD}"
      PIXL_DB_NAME: "${PIXL_DB_NAME}"
      <<: *proxy-common
      <<: *pixl-common-env
    ports:
      - "${ORTHANC_RAW_DICOM_PORT}:4242"
      - "${ORTHANC_RAW_WEB_PORT}:8042"
    volumes:
      - type: volume
        source: orthanc-raw-data
        target: /var/lib/orthanc/db
      - ${PWD}/orthanc/orthanc-raw/config:/run/secrets:ro
    networks:
      - pixl-net
    restart: "no"

  patient-queue:
    build:
      context: .
      dockerfile: ./docker/patient-queue/Dockerfile
    env_file:
      - ./docker/patient-queue/.env
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_ADMIN_PORT}:15672"
    restart: on-failure

#  rabbitmq:
#    build:
#      context: .
#      dockerfile: ./docker/patient-queue/Dockerfile
#      args:
#        <<: *build-args-common
#    env_file:
#      - ./docker/patient-queue/.env
#    ports:
#      - "${RABBITMQ_PORT}:5672"
#      - "${RABBITMQ_ADMIN_PORT}:15672"
#    restart: on-failure

  ################################################################################
  # Data Stores
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
      args:
        <<: *build-args-common
    environment:
      POSTGRES_USER: ${PIXL_DB_USER}
      POSTGRES_PASSWORD: ${PIXL_DB_PASSWORD}
      PIXL_DB_NAME: ${PIXL_DB_NAME}
      PGTZ: Europe/London
    env_file:
      - ./docker/common.env
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${PIXL_DB_PORT}"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PIXL_DB_USER}" ]
      interval: 10s
      timeout: 30s
      retries: 5
    restart: always
    networks:
      - pixl-net
