[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pixl"
version = "0.2.0rc0"
requires-python = "==3.11.9"
dependencies = [
    "core==0.2.0rc0",
    "hasher==0.2.0rc0",
    "pixl_cli==0.2.0rc0",
    "pixl_dcmd==0.2.0rc0",
    "pixl_export==0.2.0rc0",
    "pixl_imaging==0.2.0rc0",
    "pytest-pixl==0.2.0rc0",
]

[tool.uv]
dev-dependencies = [
    "dcm2niix==1.0.20220715",
    "httpx==0.27",
    "nibabel==5.2.1",
    "pytest==8.3.2",
    "pytest-asyncio==0.23.8",
    "pytest-check==2.3.1",
    "pytest-cov==5.0.0",
    "pytest-mock==3.14",
    "pytest-pixl==0.2.0rc0",
    "xnat4tests==0.3.11",
    "mypy",
    "pre-commit",
    "ruff",
]

[tool.uv.sources]
core = { workspace = true }
hasher = { workspace = true }
pixl_cli = { workspace = true }
pixl_dcmd = { workspace = true }
pixl_export = { workspace = true }
pixl_imaging = { workspace = true }
pytest-pixl = { workspace = true }

[tool.uv.workspace]
members = [
    "pixl_core",
    "cli",
    "hasher",
    "pixl_dcmd",
    "pixl_export",
    "pixl_imaging",
    "pytest-pixl",
]

[tool.setuptools]
packages = []
