project:
    name: "project-slug"
    modalities: ["DX", "CR"] # DICOM dataset modalities to retain

tag_operation_files: ["base-tag-operations.yaml"] # DICOM tag anonymisation operations, can specify multiple files

destination:
    dicom: "ftps" # alternatives: "none", "dicomweb", "azure"
    parquet: "ftps" # alternatives: "none", "azure"
