FROM apachepulsar/pulsar:2.10.2

# RUN exec bash
# RUN /pulsar/bin/pulsar-admin topics create persistent://public/default/ehrs
# RUN /pulsar/bin/pulsar-admin topics create persistent://public/default/ehrs
# potentially append to end of file echo "brokerDeleteInactiveTopicsEnabled=false" >> /pulsar/conf/bookkeeper.conf?

SHELL ["/bin/bash", "-o", "pipefail", "-e", "-u", "-x", "-c"]