[project]
name = "pixl_cli"
version = "0.0.4"
authors = [
  { name="PIXL authors" },
]
description = "PIXL command line interface"
readme = "README.md"
requires-python = "<3.12"
classifiers = [
    "Programming Language :: Python :: 3"
]
dependencies = [
    "core",
    "click==8.1.3",
    "coloredlogs==15.0.1",
    "pandas==1.5.1",
    "pyarrow==14.0.1",
    "PyYAML==6.0.1"
]

[project.optional-dependencies]
test = [
    "pytest==7.4.*"
]
dev = [
    "mypy",
    "pre-commit",
    "ruff",
]

[project.scripts]
pixl = "pixl_cli.main:cli"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
