#  Copyright (c) University College London Hospitals NHS Foundation Trust
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Example tags obtained from https://github.com/rordenlab/dcm2niix/blob/master/Philips/README.md#diffusion-direction
# https://www.documents.philips.com/doclib/enc/fetch/8554818/DICOM_Conformance_Statement_MR_Applications_on_IntelliSpace_Portal_V4.0.pdf
- manufacturer: ^philips
  tags:
    - name: "Private Creator Group 2001"
      group: 0x2001
      element: 0x0010
      op: "keep"
    - name: "Private Creator Group 2001 (90)"
      group: 0x2001
      element: 0x0090
      op: "keep"
    - name: "Diffusion B-Factor"
      group: 0x2001
      element: 0x1003
      op: "keep"
    - name: "Private Creator Group 2005"
      group: 0x2005
      element: 0x0010
      op: "keep"
    - name: "Diffusion Direction RL"
      group: 0x2005
      element: 0x10b0
      op: "keep"
    - name: "Diffusion Direction AP"
      group: 0x2005
      element: 0x10b1
      op: "keep"
    - name: "Diffusion Direction FH"
      group: 0x2005
      element: 0x10b2
      op: "keep"

# Example tags obtained from https://github.com/rordenlab/dcm2niix/blob/master/Siemens/README.md#siemens-x-series
- manufacturer: ^siemens
  tags:
    - name: "SIEMENS MR HEADER private creator Group"
      group: 0x0019
      element: 0x0010
      op: "keep"
    - name: "SiemensDiffusionBValue"
      group: 0x0019
      element: 0x100c
      op: "keep"
    - name: "SiemensDiffusionGradientOrientation"
      group: 0x0019
      element: 0x100e
      op: "keep"
    - name: "SIEMENS CSA HEADER private creator"
      group: 0x0029
      element: 0x0010
      op: "keep"
    - name: "SIEMENS MEDCOM HEADER2  private creator"
      group: 0x0029
      element: 0x0011
      op: "keep"
    - name: "CSA Image Header Info"
      group: 0x0029
      element: 0x1010
      op: "keep"
    - name: "CSA Series Header Info"
      group: 0x0029
      element: 0x1020
      op: "keep"
