#  Copyright (c) University College London Hospitals NHS Foundation Trust
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
FROM python:3.10.6-slim-bullseye
SHELL ["/bin/bash", "-o", "pipefail", "-e", "-u", "-x", "-c"]

# source code
COPY ./patient_queue/src ./patient_queue
COPY ./token_buffer/src ./token_buffer
RUN pip install -r ./patient_queue/requirements.txt
RUN pip install -r ./token_buffer/requirements.txt
RUN pip install --no-cache-dir ./token_buffer && \
    pip install --no-cache-dir ./patient_queue
