project:
    name: "myproject"
    modalities: ["DX", "CR"]

tag_operation_files:
    [
        "base-tag-operations.yaml",
        "example-tag-operations.yaml",
        "extension-tag-operations.yaml",
    ]

destination:
    dicom: "ftps"
    parquet: "ftps"
