"""<Description of changes to models>

Revision ID: d947cc715eb1
Revises: 83dcb3812628
Create Date: 2024-08-21 11:42:57.946914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd947cc715eb1'
down_revision: Union[str, None] = '83dcb3812628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('pseudo_patient_id', sa.String(length=255), nullable=True), schema='pipeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'pseudo_patient_id', schema='pipeline')
    # ### end Alembic commands ###
