[project]
name = "core"
version = "0.1.0"
authors = [{ name = "PIXL core functionality" }]
description = ""
readme = "README.md"
requires-python = ">=3.9"
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
    "azure-identity==1.16.1",
    "azure-keyvault==4.2.0",
    "fastapi==0.112.0",
    "token-bucket==0.3.0",
    "python-decouple==3.8",
    "python-slugify==8.0.4",
    "pika==1.3.2",
    "aio_pika==9.4.2",
    "requests==2.32.2",
    "jsonpickle==3.2.2",
    "loguru==0.7.2",
    "sqlalchemy==2.0.32",
    "psycopg2-binary==2.9.9",
    "pandas==2.2.2",
    "pyarrow==17.0.0",
    "PyYAML==6.0.1",
    "pydantic==2.8.2",
]

[project.optional-dependencies]
test = [
    "pytest==8.3.2",
    "pytest-cov==5.0.0",
    "pytest-asyncio==0.23.8",
    "httpx==0.27.*",
    "pytest-pixl==0.1.0",
]
dev = ["mypy", "pre-commit", "ruff"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = ["pika"]

[tool.ruff]
extend = "../ruff.toml"

[tool.ruff.lint.extend-per-file-ignores]
"./tests/**" = ["D100"]


[tool.coverage.report]
exclude_also = [
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "except subprocess.CalledProcessError as exception:",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "if typing.TYPE_CHECKING",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]