[project]
name = "hasher"
version = "0.0.1"
authors = [{ name = "PIXL authors" }]
description = "Service to securely hash identifiers"
readme = "README.md"
requires-python = ">=3.10"
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
    "core",
    "azure-identity==1.16.1",
    "azure-keyvault==4.2.0",
    "fastapi==0.109.1",
    "hypothesis==6.56.0",
    "requests==2.31.0",
    "uvicorn==0.23.2",
]

[project.optional-dependencies]
test = ["pytest==7.4.*", "httpx==0.24.*"]
dev = ["mypy", "pre-commit", "ruff"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
extend = "../ruff.toml"

[tool.ruff.lint.extend-per-file-ignores]
"./tests/**" = ["D1"]
"./src/hasher/endpoints.py" = ["D103"]
