#  Copyright (c) University College London Hospitals NHS Foundation Trust
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
name: pixl-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ensure copyright and license header are present
        run: ./.github/linters/check_headers_exist.sh

      - name: Validate Docker Compose config file
        working-directory: .
        run: |
          cp .env.sample .env
          docker compose config --quiet

  hasher-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r hasher/src/requirements.txt

      - name: Run tests
        working-directory: hasher
        run: |
          bin/run-tests.sh
        env:
          ENV: test
          AZURE_KEY_VAULT_NAME: test
          AZURE_KEY_VAULT_SECRET_NAME: test

  report-de-id-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'  # Numpy croaks on 3.10.7+
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pixl_rd/src/requirements.txt

      - name: Download presidio data
        run: |
          python -m spacy download en_core_web_lg

      - name: Run tests
        working-directory: pixl_rd
        run: |
          bin/run-tests.sh
        env:
          ENV: test

  token-buffer-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r token_buffer/src/requirements.txt

      - name: Run tests
        working-directory: token_buffer
        run: |
          bin/run-tests.sh
        env:
          ENV: test

  dicom-de-id-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pixl_dcmd/src/requirements.txt

      - name: Run tests
        working-directory: pixl_dcmd
        run: |
          bin/run-tests.sh
        env:
          ENV: test

  patient-queue-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r patient_queue/src/requirements.txt

      - name: Run tests
        working-directory: patient_queue
        run: |
          bin/run-tests.sh
        env:
          ENV: test

  cli-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r cli/src/requirements.txt
          pip install -r patient_queue/src/requirements.txt
          pip install patient_queue/src/

      - name: Run tests
        working-directory: cli/test
        run: |
          ./run-tests.sh


  ehr-api-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pixl_ehr/src/requirements.txt
          pip install -r pixl_rd/src/requirements.txt pixl_rd/src/
          pip install -r token_buffer/src/requirements.txt token_buffer/src/
          pip install -r patient-queue/src/requirements.txt patient_queue/src/
          python -m spacy download en_core_web_lg

      - name: Run tests
        working-directory: pixl_ehr/test
        run: |
          ./run-tests.sh
