name: pixl-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:

  validate-docker-compose-config-file:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate Docker Compose config file
        working-directory: .
        run: |
          cp .env.sample .env
          docker compose config --quiet

  hasher-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r hasher/src/requirements.txt

      - name: Run tests
        working-directory: hasher
        run: |
          bin/run-tests.sh
        env:
          ENV: test
          AZURE_KEY_VAULT_NAME: test
          AZURE_KEY_VAULT_SECRET_NAME: test

  report-de-id-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'  # Numpy croaks on 3.10.7+
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pixl_rd/src/requirements.txt

      - name: Download presidio data
        run: |
          python -m spacy download en_core_web_lg

      - name: Run tests
        working-directory: pixl_rd
        run: |
          bin/run-tests.sh
        env:
          ENV: test

  token-buffer-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r token_buffer/src/requirements.txt

      - name: Run tests
        working-directory: token_buffer
        run: |
          bin/run-tests.sh
        env:
          ENV: test

  dicom-de-id-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pixl_dcmd/src/requirements.txt

      - name: Run tests
        working-directory: pixl_dcmd
        run: |
          bin/run-tests.sh
        env:
          ENV: test


  cli-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r cli/src/requirements.txt

      - name: Run tests
        working-directory: cli/test
        run: |
          ./run-tests.sh


  ehr-api-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pixl_ehr/src/requirements.txt
          pip install -r pixl_rd/src/requirements.txt pixl_rd/src/
          python -m spacy download en_core_web_lg

      - name: Run tests
        working-directory: pixl_ehr/test
        run: |
          ./run-tests.sh
