name: pixl-ci

on:
  push:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:

  validate-docker-compose-config-file:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate Docker Compose config file
        working-directory: .
        run: |
          cp .env.sample .env
          docker compose config --quiet

  hasher-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.7
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r hasher/src/requirements.txt
      - name: Run tests
        working-directory: hasher/src
        run: |
          bin/run-tests.sh
        env:
          PIXL_ENV: test
