name: pixl-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:

  driver-tests:
    runs-on: uclhdif-runner
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.7
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r driver/src/requirements.txt

      - name: Run tests
        working-directory: driver/test
        run: |
          ${{ github.workspace }}/driver/test/run-tests.sh
